### ISSUE TITLE
Resetting not working as intended

### ISSUE THREAD

**Issue by muhalufa** [bradleyjm/Tafe18S103#2]
In the settings page, although the feature table for my appointments has been added to the 'dropTable' list. It is not resetting the data once the reset button is pressed.

**Comment by bradleyjm** [comment]
sqlFindata.sqllite should be Findata.sqlite at AppointmentPage.xaml.cs

**Comment by bayton734** [comment]
I had the same issue. My solution was different - I had not made my Contact model class as public.
